import Head from 'next/head'
import { CHAINS_CONFIG } from "lib/constants"
import { CHAINS, ChainType } from 'types'
import Arweave from 'components/App'

type StaticPropsT = {
    params : { chain : CHAINS }
}
export async function getStaticProps({ params }: StaticPropsT) {
    const chainId = params.chain
    const chainConfig = CHAINS_CONFIG[chainId]
    return {
        props: {
            chainConfig,
        },
    }
}

export async function getStaticPaths() {
    return {
        paths: Object.values(CHAINS_CONFIG).map((chain) => { return { params: { chain: chain.id } } } ),
        fallback: false
  };
}

type ChainT = {
    chainConfig: ChainType
}
export default function Chain({ chainConfig }: ChainT) {
    const chainLabel = chainConfig.label;

    return (
        <>
            <Head>
                <title>{`Figment Learn - ${chainLabel} Pathway`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Arweave chain={ chainConfig }/>
        </>
    )
}
