import Head from 'next/head'
import dynamic from 'next/dynamic'
import { CHAINS_CONFIG } from "lib/constants"
import { CHAINS } from 'types'
import styled from "styled-components";
import { SyncOutlined } from '@ant-design/icons';



export default function Chain() {
    const chainConfig = CHAINS_CONFIG[CHAINS.ARWEAVE];

    const Spinner = () => {
        return (
            <SpinContainer>
                <SyncOutlined style={{  fontSize: '64px' }} spin />
            </SpinContainer>
        )
    }

    const dynOptions = { loading: function spinner(){ return ( <Spinner /> ) }, ssr: false };
    const DynArweave = dynamic(() => import('components'), dynOptions);

    return (
        <>
            <Head>
                <title>{`Arweave Crash Course`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DynArweave chain={ chainConfig }/>
        </>
    )
}

const SpinContainer = styled.div`
    display: flex;
    min-height: 100vh;
    justify-content: center;
    align-items: center;
`;
