import Head from 'next/head'
import React from "react";
import Link from "next/link";
import { Col } from 'antd';
import styled from "styled-components";
import { CHAINS } from "types";
import { CHAINS_CONFIG } from "lib/constants";

function getChainColors() {
    return { bgColor: "black", textColor: "white"}
}

const Home = () => {
    const { id, active, logoUrl, label } = CHAINS_CONFIG[CHAINS.ARWEAVE];
    const { bgColor, textColor } = getChainColors()

    const box = (
        <ProtocolBox key={id} active={active} bg_color={bgColor} text_color={textColor}>
            {label === "Polygon" ? <PolygonLogo /> : <Logo src={logoUrl} />}
            <Label>{label}</Label>
        </ProtocolBox>
    );

	return (
		<Container span={12} offset={6}>
			<Title>Figment Learn - All Pathways</Title>
			<ChainRow>
                { active ? <Link href='/crash' key={id}>{box}</Link> : box }
			</ChainRow>
		</Container>
	)
}

const Container = styled(Col)`
	margin-top: 60px;
`;

const Title = styled.h1`
	margin-bottom: 40px;
`;

const ChainRow = styled.div`
	display: grid;
	grid-template-columns: 1fr 1fr 1fr;
	column-gap: 20px;
	row-gap: 20px;
`;

const ProtocolBox = styled.div<{ active: boolean; bg_color: string; text_color: string }>`
	height: 170px;
	border: solid 1px #eee;
	background-color: #f8f8f8;
	border-radius: 5px;

	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	opacity: ${({ active }) => active ? 1 : 0.4};

	${({ active, bg_color, text_color }) => active && `
		&:hover {
			border: none;
			color: ${text_color};
			background: ${bg_color};
			cursor: pointer;
		}
		&:hover > svg {
            path {
                fill: #ffffff
            }
        }

	`}
`;

const Logo = styled.img`
	height: 50px;
	margin-bottom: 20px;
`;

const Label = styled.div`
	font-size: 18px;
	font-weight: 500;
`;

const PolygonLogo = () => 
    <PolygonSVG x="0px" y="0px" viewBox="0 0 38.4 33.5" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M29,10.2c-0.7-0.4-1.6-0.4-2.4,0L21,13.5l-3.8,2.1l-5.5,3.3c-0.7,0.4-1.6,0.4-2.4,0L5,16.3
        c-0.7-0.4-1.2-1.2-1.2-2.1v-5c0-0.8,0.4-1.6,1.2-2.1l4.3-2.5c0.7-0.4,1.6-0.4,2.4,0L16,7.2c0.7,0.4,1.2,1.2,1.2,2.1v3.3l3.8-2.2V7
        c0-0.8-0.4-1.6-1.2-2.1l-8-4.7c-0.7-0.4-1.6-0.4-2.4,0L1.2,5C0.4,5.4,0,6.2,0,7v9.4c0,0.8,0.4,1.6,1.2,2.1l8.1,4.7
        c0.7,0.4,1.6,0.4,2.4,0l5.5-3.2l3.8-2.2l5.5-3.2c0.7-0.4,1.6-0.4,2.4,0l4.3,2.5c0.7,0.4,1.2,1.2,1.2,2.1v5c0,0.8-0.4,1.6-1.2,2.1
        L29,28.8c-0.7,0.4-1.6,0.4-2.4,0l-4.3-2.5c-0.7-0.4-1.2-1.2-1.2-2.1V21l-3.8,2.2v3.3c0,0.8,0.4,1.6,1.2,2.1l8.1,4.7
        c0.7,0.4,1.6,0.4,2.4,0l8.1-4.7c0.7-0.4,1.2-1.2,1.2-2.1V17c0-0.8-0.4-1.6-1.2-2.1L29,10.2z" fill="#8247E5"/>
    </PolygonSVG>

const PolygonSVG = styled.svg`
	height: 50px;
	margin-bottom: 20px;
`;


export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  )
}
